Add support for doctrine/persistence 2.x
sonata-project/SonataClassificationBundle pull request #599
Opened 2020-10-09 21:32 UTC by awurth

## Subject

Allow version 2 for "doctrine/persistence".

I am targeting this branch, because this change respects BC.

## Changelog

```markdown
### Added
- Added support for "doctrine/persistence:^2.0".
```

2020-10-10 09:09 UTC, jordisala1991 commented
It would be nice to have doctrine / persistence as a dev dependency at least (supporting both 1.3 and 2)

2020-10-10 10:27 UTC, core23 requested changes

2020-10-10 10:27 UTC, core23 commented on src/Entity/CategoryManager.php
> +use Doctrine\Persistence\ManagerRegistry;
Changing this, requires `doctrine/perstience` as a non-dev dependency

2020-10-10 10:54 UTC, jordisala1991 approved these changes

2020-10-10 12:17 UTC, VincentLanglet approved these changes

2020-10-10 13:18 UTC, core23 approved these changes

2020-10-10 13:20 UTC, VincentLanglet commented
Thanks

2020-10-10 13:20 UTC, merged

2020-11-25 07:28 UTC, OskarStark commented
/request-release

2020-11-25 07:28 UTC, SonataCI commented
Ok @OskarStark,

I requested a new release for **SonataClassificationBundle** via Slack in `#releases` channel :+1:

_If you want to get notified about new releases, make sure to follow [SonataNews](https://twitter.com/sonatanews) on Twitter!_