Add type hints to methods and properties
sonata-project/SonataClassificationBundle pull request #745
Opened 2021-10-13 20:18 UTC by core23

## Subject

I am targeting this branch, because this is a BC break.

## Changelog

```markdown
### Changed
- Added type hints to methods and properties
- Reduce visibility of config methods

### Removed
- Removed `Sonata\ClassificationBundle\Form\FormHelper`
```

2021-10-14 07:42 UTC, VincentLanglet submitted a review, later dismissed

2021-10-14 17:26 UTC, wbloszyk requested changes

2021-10-14 17:26 UTC, wbloszyk commented on src/Entity/CategoryManager.php
> +    public function getSubCategoriesPager(int $categoryId, int $page = 1, int $limit = 25, array $criteria = []): Pager
IMO we should not define `catrgoryId` type and aby other id field.

2021-10-14 17:58 UTC, ChristianGripp commented on src/Entity/CategoryManager.php
> +    public function getSubCategoriesPager(int $categoryId, int $page = 1, int $limit = 25, array $criteria = []): Pager
Fixed

2021-10-14 17:59 UTC, wbloszyk submitted a review, later dismissed

2021-10-19 07:17 UTC, VincentLanglet commented on Makefile
> +
weird

2021-10-19 07:20 UTC, VincentLanglet commented on psalm-baseline.xml
> +    <file src="src/Block/Service/AbstractClassificationBlockService.php">
What is the issue with all of this ? Can't we fix those ?

2021-10-19 07:48 UTC, ChristianGripp commented on Makefile
> +
Indeed. The last change on the 4.x build successfully

2021-10-19 17:36 UTC, VincentLanglet reviewed
Can't we fix the baseline instead of generating it ?

2021-10-19 19:15 UTC, ChristianGripp commented on psalm-baseline.xml
> +        <QueryBuilderSetParameter occurrences="2">
Not sure how to fix this. The context can be a string type or a context instance.

2021-10-19 19:35 UTC, VincentLanglet commented on psalm-baseline.xml
> +        <QueryBuilderSetParameter occurrences="2">
Do you know where/how are used the getBySlug and getByContext method ?

First, It could be great to have a method only accepting string or Context instance but not both. But that shouldn't be a general blocker but it might have sens here.

If I remember correctly calling `setParameter` on an object is kinda the same than calling setParameter and passing the id of this object. Which means that the string that can be passed to this method must be the id of the context, not the name of the method, this can be confusing.

Anyway. Passing an object to `setParameter` without specifying a type is not recommended for perf issues. https://twitter.com/Ocramius/status/1251478780381716480

Best would be to call getId on it if it's an object.

2021-10-19 20:01 UTC, ChristianGripp commented on psalm-baseline.xml
> +        <QueryBuilderSetParameter occurrences="2">
> First, It could be great to have a method only accepting string or Context instance but not both. But that shouldn't be a general blocker but it might have sens here.

Did not find any usage for a context object parameter, so I changed this to string only.

2021-10-19 20:16 UTC, VincentLanglet commented on psalm-baseline.xml
> +        <QueryBuilderSetParameter occurrences="2">
Then we can rename it contextId

2021-10-19 20:20 UTC, ChristianGripp commented on psalm-baseline.xml
> +        <QueryBuilderSetParameter occurrences="2">
> Then we can rename it contextId

We should keep the name as it is. We  use `context` across all bundles when talking about the string representation.

2021-10-19 20:45 UTC, VincentLanglet commented on psalm-baseline.xml
> +        <QueryBuilderSetParameter occurrences="2">
Do you have some example ?

Because when I look at the code in the ClassificationBundle I see code like
```
/* @var ContextInterface $context */
foreach ($this->contextManager->findAll() as $context) {
    $contextChoices[(string) $context->getId()] = (string) $context->getName();
}
```

So it doesn't seem a bad thing to use `contextId` for the string representation. And it's not because the mistake was made somewhere else, that we should keep it forever. The 4.0 release might be the right time to fix it everywhere.

Fact is I don't use other bundle, and I don't know what is this context. I looked at the MediaBundle to ask the opinion of @jordisala1991 but seems like all the `string $context` usage are related to a real string value. A media has a context property, not a ContextInterface one.

2021-10-20 11:02 UTC, ChristianGripp commented on psalm-baseline.xml
> +        <QueryBuilderSetParameter occurrences="2">
> Do you have some example ?

When searching for `context` inside the media bundle, there are several findings:
https://github.com/sonata-project/SonataMediaBundle/blob/26991351cac2b1399890685b43c4d20efc69da11/src/Block/GalleryListBlockService.php#L79
https://github.com/sonata-project/SonataMediaBundle/blob/cafbe30674803dd5bfebd6f6e7cfbbf5cafb5e6d/src/Admin/GalleryAdmin.php#L69
https://github.com/sonata-project/SonataNewsBundle/blob/75b0c68e9bb77d75f0605520eb1af12c63071b36/src/Admin/PostAdmin.php#L122

There are some more, but I'm lazy to link every code fragment ;)

> A media has a context property, not a ContextInterface one.

That's right, but the context property of a media instance is linked to the context id of the `ContextInterface`:

https://github.com/sonata-project/SonataMediaBundle/blob/961e51a0da4b0be82ca0ada2644422f918c4e6f2/src/Command/FixMediaContextCommand.php#L70-L72

2021-10-22 08:44 UTC, core23 commented
Please review @sonata-project/contributors 

I'd like to release a first alpha version soon

2021-10-22 13:29 UTC, wbloszyk submitted a review, later dismissed

2021-10-26 15:35 UTC, ChristianGripp commented on src/Block/Service/AbstractClassificationBlockService.php
> + * @phpstan-template T of object of ContextAwareInterface
Looks like psalm has some problem with this :/

Can someone help or should we ignore this error?

2021-10-26 15:55 UTC, VincentLanglet commented on src/Block/Service/AbstractClassificationBlockService.php
> + * @phpstan-template T of object of ContextAwareInterface
Didnt take a big look, but I would say you want to do
```
@phpstan-template T of ContextAwareInterface
```

2021-10-26 16:39 UTC, ChristianGripp commented on src/Block/Service/AbstractClassificationBlockService.php
> +     * @phpstan-param AdminInterface<T> $admin
The admin generic requires and object and no interface:
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Admin/AbstractAdmin.php#L55

2021-10-26 16:40 UTC, ChristianGripp commented on src/Block/Service/AbstractClassificationBlockService.php
> + * @phpstan-template T of object of ContextAwareInterface
This does not work (see: https://github.com/sonata-project/SonataClassificationBundle/pull/745/files/0bd9a6a6e7603b70db4608365f00c3c6e313fc54#r736730231)

2021-10-26 19:25 UTC, VincentLanglet commented on src/Block/Service/AbstractClassificationBlockService.php
> + * @phpstan-template T of object of ContextAwareInterface
The class considered is `objectofContextAwareInterface`.

It should work with `phpstan-template T of ContextAwareInterface` https://psalm.dev/r/97f4adf72f

2021-10-26 19:26 UTC, VincentLanglet commented on src/Block/Service/AbstractClassificationBlockService.php
> +     * @phpstan-param AdminInterface<T> $admin
This shouldnt be an issue https://psalm.dev/r/97f4adf72f

2021-10-26 19:43 UTC, ChristianGripp commented on src/Block/Service/AbstractClassificationBlockService.php
> +     * @phpstan-param AdminInterface<T> $admin
Now we got a different error, because an interface generic is not an object generic :/

2021-10-26 19:53 UTC, VincentLanglet commented on src/Block/Service/AbstractClassificationBlockService.php
> +     * @phpstan-param AdminInterface<T> $admin
This is a "normal" error, because phpstan considered that the Admin must support any object, because we used `AdminInterface<object>`.

We solve this by making the whole class generic, or sometimes juste making the method kinda-generic https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Admin/AdminHelper.php#L87-L91

I think that chanigng setAdmin and setAssociationAdmin the same way could solve those errors.

2021-10-27 06:19 UTC, ChristianGripp commented on src/Block/Service/AbstractClassificationBlockService.php
> +     * @phpstan-param AdminInterface<T> $admin
This should fix it: https://github.com/sonata-project/SonataAdminBundle/pull/7558

2021-10-28 15:40 UTC, VincentLanglet submitted a review, later dismissed

2021-10-28 17:43 UTC, phansys commented on psalm.xml
> +<psalm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://getpsalm.org/schema/config" errorLevel="6" resolveFromConfigFile="true" xsi:schemaLocation="https://getpsalm.org/schema/con
Is it fine to reduce the introspection level?

2021-10-28 17:48 UTC, phansys commented on tests/Entity/TagManagerTest.php
> +    private function getTagManager(\Closure $qbCallback): TagManager
Do we need to force the passed callable to be anonymous? Otherwise, I think we should use `callable` instead.

2021-10-28 18:04 UTC, VincentLanglet commented on psalm.xml
> +<psalm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://getpsalm.org/schema/config" errorLevel="6" resolveFromConfigFile="true" xsi:schemaLocation="https://getpsalm.org/schema/con
In psalm 6 is stricter than 8

2021-10-28 18:08 UTC, phansys commented on psalm.xml
> +<psalm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://getpsalm.org/schema/config" errorLevel="6" resolveFromConfigFile="true" xsi:schemaLocation="https://getpsalm.org/schema/con
:baby_chick:

2021-10-28 18:08 UTC, ChristianGripp commented on tests/Entity/TagManagerTest.php
> +    private function getTagManager(\Closure $qbCallback): TagManager
The `createEntityManagerMock` method requires a closure parameter

2021-10-28 18:08 UTC, phansys commented on psalm.xml
> +<psalm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://getpsalm.org/schema/config" errorLevel="6" resolveFromConfigFile="true" xsi:schemaLocation="https://getpsalm.org/schema/con
Thank you for the clarification.

2021-10-28 18:09 UTC, phansys submitted a review, later dismissed

2021-10-28 18:21 UTC, core23 commented
Bumped phpstan to from level 4 to 6 and psalm down from 8 to 4.

IMHO the rest is nice to have and should not block a new release.

2021-10-28 18:25 UTC, VincentLanglet commented
> Bumped phpstan to from level 4 to 6 and psalm down from 8 to 4.
> 
> IMHO the rest is nice to have and should not block a new release.

Let's merge this and I'll take quickly a look at what's missing to bump the static analysis.

2021-10-28 18:41 UTC, VincentLanglet reviewed
Why do we provide `getRootCategoriesPager` and `getSubCategoriesPager` in the interface if we don't use them ?

I think those method should be removed.

2021-10-28 19:00 UTC, VincentLanglet commented
Also, all the public/protected method from abstract classes can be made final (but can be made in another PR)

2021-10-28 19:23 UTC, VincentLanglet commented
The error
```
Parameter #1 $formMapper of method Sonata\ClassificationBundle\Block\Service\AbstractClassificationBlockService<Sonata\ClassificationBundle\Model\TagInterface>::getFormAdminType() expects  
         Sonata\AdminBundle\Form\FormMapper<Sonata\ClassificationBundle\Model\TagInterface>, Sonata\BlockBundle\Form\Mapper\FormMapper given.
```
is interesting. The typehint accepts `Sonata\BlockBundle\Form\Mapper\FormMapper` but we're using it like it's the AdminBundle interface.

Making EditableBlockService a generic
```
/**
 * @author Christian Gripp <mail@core23.de>
 *         
 * @phpstan-template T of FormMapper
 */
interface EditableBlockService
{
    /** @phpstan-param T $form */
    public function configureEditForm(FormMapper $form, BlockInterface $block): void;

    /** @phpstan-param T $form */
    public function configureCreateForm(FormMapper $form, BlockInterface $block): void;

    public function validate(ErrorElement $errorElement, BlockInterface $block): void;

    public function getMetadata(): MetadataInterface;
}
```

```
@phpstan-implements EditableBlockService<\Sonata\AdminBundle\Form\FormMapper<TagInterface>>
```
on AbstractTagsBlockService solve the issue.

2021-10-28 19:28 UTC, VincentLanglet commented
There is a call `$category->disableChildrenLazyLoading();` which doesn't exist on the interface ; and we need to solve this.

I made a commit bumping phpstan to 8 and psalm to 3. There is still some errors to fix but lot of them are done.
https://github.com/VincentLanglet/SonataClassificationBundle/commit/322a17efa0e4c8032520265070b9828ee418f3a8

2021-10-28 20:03 UTC, core23 commented
> Why do we provide `getRootCategoriesPager` and `getSubCategoriesPager` in the interface if we don't use them ?


> Also, all the public/protected method from abstract classes can be made final (but can be made in another PR)


Not related to this PR

> The typehint accepts `Sonata\BlockBundle\Form\Mapper\FormMapper` but we're using it like it's the AdminBundle interface.

This is indeed a problem. I'll try to fix this with the next PR.

2021-10-28 20:05 UTC, VincentLanglet commented
> > Why do we provide `getRootCategoriesPager` and `getSubCategoriesPager` in the interface if we don't use them ?
> 
> > Also, all the public/protected method from abstract classes can be made final (but can be made in another PR)
> 
> Not related to this PR
> 
> > The typehint accepts `Sonata\BlockBundle\Form\Mapper\FormMapper` but we're using it like it's the AdminBundle interface.
> 
> This is indeed a problem. I'll try to fix this with the next PR.

Sure I was just using the PR to list the to do for the final 4.0 release.

2021-10-28 20:05 UTC, VincentLanglet approved these changes

2021-10-31 19:32 UTC, merged