Remove call to unknown method
sonata-project/SonataClassificationBundle pull request #757
Opened 2021-10-28 20:10 UTC by core23

## Subject

We don't need this call, as the admin is set via https://github.com/sonata-project/SonataAdminBundle/blob/ab9f4e0771e303628d0ea3fe99b0b56cb7b07895/src/Admin/AbstractAdmin.php#L1824

## Changelog

```markdown
### Fixed
- Removed call to unknown `FormMapper::getAdmin` method 
```

2021-10-28 20:15 UTC, phansys submitted a review, later dismissed

2021-10-28 20:18 UTC, VincentLanglet requested changes

2021-10-28 20:18 UTC, VincentLanglet commented on src/Block/Service/AbstractClassificationBlockService.php
> -        $fieldDescription->setAdmin($formMapper->getAdmin());
Can the FormMapper namespace be changed to the BlockBundle one ?

2021-10-29 05:47 UTC, VincentLanglet approved these changes

2021-10-29 06:06 UTC, merged