Prepare 4.0.0-alpha-1 release
sonata-project/SonataClassificationBundle pull request #758
Opened 2021-10-31 20:21 UTC by core23

2021-10-31 20:21 UTC, core23 commented on CHANGELOG.md
> +## [4.0.0-alpha-1](https://github.com/sonata-project/SonataClassificationBundle/compare/3.17.0...4.0.0-alpha-1) - 2021-11-01
Predated this to tomorrow

2021-10-31 20:58 UTC, phansys approved these changes, later dismissed

2021-10-31 20:58 UTC, phansys commented on CHANGELOG.md
> +- [[#754](https://github.com/sonata-project/SonataClassificationBundle/pull/754)] Add type hints to manager methods ([@core23](https://github.com/core23))
```suggestion
- [[#754](https://github.com/sonata-project/SonataClassificationBundle/pull/754)] Type hints to manager methods ([@core23](https://github.com/core23))
```

2021-10-31 20:58 UTC, phansys commented on CHANGELOG.md
> +- [[#753](https://github.com/sonata-project/SonataClassificationBundle/pull/753)] Added `ContextAwareInterface` ([@core23](https://github.com/core23))
```suggestion
- [[#753](https://github.com/sonata-project/SonataClassificationBundle/pull/753)] `ContextAwareInterface` ([@core23](https://github.com/core23))
```

2021-10-31 20:58 UTC, phansys commented on CHANGELOG.md
> +- [[#745](https://github.com/sonata-project/SonataClassificationBundle/pull/745)] Removed `Sonata\ClassificationBundle\Form\FormHelper` ([@core23](https://github.com/core23))
```suggestion
- [[#745](https://github.com/sonata-project/SonataClassificationBundle/pull/745)] `Sonata\ClassificationBundle\Form\FormHelper` ([@core23](https://github.com/core23))
```

2021-10-31 20:58 UTC, phansys commented on CHANGELOG.md
> +- [[#744](https://github.com/sonata-project/SonataClassificationBundle/pull/744)] Dropped support for PHP 7.3 ([@core23](https://github.com/core23))
```suggestion
- [[#744](https://github.com/sonata-project/SonataClassificationBundle/pull/744)] Support for PHP 7.3 ([@core23](https://github.com/core23))
```

2021-10-31 23:09 UTC, phansys approved these changes, later dismissed

2021-11-01 08:11 UTC, jordisala1991 commented
Can you use alpha1 like in the media-bundle?

2021-11-01 09:01 UTC, core23 commented
We have three different version names at the moment (created by three different people):

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/releases/tag/4.0.0-alpha-1
https://github.com/sonata-project/SonataSeoBundle/releases/tag/3.0.0-alpha.1
https://github.com/sonata-project/SonataMediaBundle/releases/tag/4.0.0-alpha1

Not sure what is the *right* one.

2021-11-01 09:16 UTC, jordisala1991 commented
> We have three different version names at the moment (created by three different people):
> 
> 
> 
> https://github.com/sonata-project/SonataDoctrineORMAdminBundle/releases/tag/4.0.0-alpha-1
> 
> https://github.com/sonata-project/SonataSeoBundle/releases/tag/3.0.0-alpha.1
> 
> https://github.com/sonata-project/SonataMediaBundle/releases/tag/4.0.0-alpha1
> 
> 
> 
> Not sure what is the *right* one.

https://getcomposer.org/doc/articles/versions.md#vcs-tags-and-branches

alpha1 from composer pov

2021-11-01 09:32 UTC, core23 commented
Changed this to `alpha1`

2021-11-01 11:22 UTC, VincentLanglet commented
I'll try to bump the static analysis but this can be done between the alpha and the stable one

2021-11-01 11:22 UTC, VincentLanglet approved these changes, later dismissed

2021-11-01 14:23 UTC, VincentLanglet commented
See https://github.com/sonata-project/SonataClassificationBundle/pull/759

2021-11-01 15:05 UTC, core23 commented
> See #759

Is this a blocking PR? There are only internal changes and no API changes.

2021-11-01 15:20 UTC, VincentLanglet commented
> > See #759
> 
> Is this a blocking PR? There are only internal changes and no API changes.

Not blocking for the alpha. It will for the RC (since we deprecate some stuff)

2021-11-01 16:42 UTC, jordisala1991 requested changes
Please include https://github.com/sonata-project/SonataClassificationBundle/pull/761

2021-11-01 19:39 UTC, VincentLanglet commented
phpstan/psalm PR is ready if you want @core23 https://github.com/sonata-project/SonataClassificationBundle/pull/759

2021-11-02 17:52 UTC, core23 commented
Please review @sonata-project/contributors. I'll plan to release this tomorrow

2021-11-02 18:42 UTC, jordisala1991 approved these changes

2021-11-02 19:30 UTC, VincentLanglet approved these changes

2021-11-03 07:04 UTC, merged