Backport changes from AdminBundle to CategoryAdminController
sonata-project/SonataClassificationBundle pull request #820
Opened 2022-02-07 20:23 UTC by core23

## Subject

There was a template error, because the `export_formats` variable does not exist.

I am targeting this branch, because this is a bugfix.

## Changelog

```markdown
### Fixed
- Backport changes from AdminBundle to `CategoryAdminController`
```

2022-02-07 20:27 UTC, VincentLanglet reviewed
Can we add a functional test to detect this bug ?

Asserting a 200 on the page should be enough in https://github.com/sonata-project/SonataClassificationBundle/blob/4.x/tests/App/Action/CartegoryAdminTest.php#L24 ?

And we could rename the file CategoryAdminTest instead of `cartegory`

2022-02-08 16:07 UTC, VincentLanglet approved these changes

2022-02-08 16:08 UTC, VincentLanglet requested changes
Seems like there is something wrong in the filter of the list url

2022-02-08 16:13 UTC, core23 commented
> Seems like there is something wrong in the filter of the list url

Fixed

2022-02-08 16:13 UTC, VincentLanglet approved these changes

2022-02-09 12:13 UTC, VincentLanglet commented
If you can review @jordisala1991 I'll merge this and create a patch release.

2022-02-10 07:06 UTC, jordisala1991 approved these changes

2022-02-10 07:06 UTC, merged

2022-02-10 07:06 UTC, jordisala1991 commented
Thanks